server:
  port: 8089
  error:
    path: /error

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: stableford-scoring-service
  security:
    oauth2:
      resourceserver:
        jwt:
          # Note the trailing slash is important!
          issuer-uri: https://connective-dev.au.auth0.com/
  datasource:
    url: jdbc:mysql://localhost:3306/polaris?useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: 'false'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
#    defer-datasource-initialization: true
  jackson:
    deserialization:
      fail-on-unknown-properties: 'false'